# MAIN base
baseURL = "/"
languageCode = "en-us"
title = "Santui Media App - Jasa Pembuatan Website Promosi"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Layanan"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Pertanyaan"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Ujungaris blok Tiga - Widasari, Indramayu."
email = "info@santuimedia.app"
phone = "+(62) 859 3345 9545"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/santuimedia"
twitter = "https://twitter.com/santuimedia"
github = "https://github.com/santuimedia"

[params]

# Header
logo = "images/logo.png"
# formspreeURL = "https://formspree.io/mjvankow"
# googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Dapatkan info terbaru"
copyright1 = "All right reserved"
copyright2 = "Copyright © Santui Media"

#contact
email = "info@santuimedia.app"